Update hyper parameters for Logistic Regression (#42)
## Describe your changes
Went over the `LogisticRegression` class to make sure things are ready
for optimization and hyperparameter altering.

## Checklist before requesting a review
- [x] The code runs successfully.

<details><summary>make run-all-models output</summary>

```
(poetry-python-project-py3.11) michaelp@MacBook-Air-3 supreme-court-ml-predictions % make run-all-models
python -m "supreme_court_predictions" --logistic-regression --random-forest --xg-boost
oh, what up?
Creating bag of words
Starting the Logistic Regression
------------------------------------------
Running a regression on case_aggregations...
Accuracy score: 0.5405405405405406
------------------------------------------
Creating bag of words
Starting the Logistic Regression
------------------------------------------
Running a regression on judge_aggregations...
Accuracy score: 0.5205479452054794
------------------------------------------
Creating bag of words
Starting the Logistic Regression
------------------------------------------
Running a regression on advocate_aggregations...
Accuracy score: 0.7567567567567568
------------------------------------------
Creating bag of words
Starting the Logistic Regression
------------------------------------------
Running a regression on adversary_aggregations...
Accuracy score: 0.7837837837837838
------------------------------------------
Creating bag of words
Starting the Random Forest
------------------------------------------
Running a random forest on case_aggregations...
Accuracy score: 0.6351351351351351
------------------------------------------
Creating bag of words
Starting the Random Forest
------------------------------------------
Running a random forest on judge_aggregations...
Accuracy score: 0.6438356164383562
------------------------------------------
Creating bag of words
Starting the Random Forest
------------------------------------------
Running a random forest on advocate_aggregations...
Accuracy score: 0.8243243243243243
------------------------------------------
Creating bag of words
Starting the Random Forest
------------------------------------------
Running a random forest on adversary_aggregations...
Accuracy score: 0.8108108108108109
------------------------------------------
Creating bag of words
Starting the XGBoost model
------------------------------------------
Error: training data is not big enough for this subset
------------------------------------------
Creating bag of words
Starting the XGBoost model
------------------------------------------
Error: training data is not big enough for this subset
------------------------------------------
Creating bag of words
Starting the XGBoost model
------------------------------------------
Error: training data is not big enough for this subset
------------------------------------------
Creating bag of words
Starting the XGBoost model
------------------------------------------
Error: training data is not big enough for this subset
------------------------------------------
(poetry-python-project-py3.11) michaelp@MacBook-Air-3 supreme-court-ml-predictions % 
```
</details>

- [x] I ran `make lint` and have made the bulk of changes that it has
requested.